version: '3.3'
services:
  application:
    image: invoicer:0.0.1
    container_name: invoicer
    env_file: .env.dev
    environment:
      - DATABASE_URL=postgres://postgres:development@postgresql/invoicer_dev
    ports:
      - 4000:4000
    depends_on:
      - postgresql
  postgresql:
    image: postgres:12-alpine
    container_name: invoicer-postgres
    environment:
      - POSTGRES_DB=invoicer_dev
      - POSTGRES_PASSWORD=development
    ports:
      - 5432:5432
    volumes:
      - invoicer_psql:/var/lib/postgresql/data
volumes:
  invoicer_psql:
